version: "3"

services:
  db:
    image: mariadb:10
    container_name: jacq-db
    environment:
      MYSQL_DATABASE: ${DB}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    expose:
      - 3306
    networks:
      - backend
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: jacq-phpmyadmin
    environment:
      PMA_ABSOLUTE_URI: http://${DEFAULT_HOST}/phpmyadmin/
    expose:
      - 80
    networks:
      - backend
      - frontend
    ports:
      - 8081:80
    links:
      - db:mysql_db_server
    restart: always

  wildfly:
    build:
      args:
        WILDFLY_USER: ${WILDFLY_USER}
        WILDFLY_PASSWORD: ${WILDFLY_PASSWORD}
      context: .
      dockerfile: Dockerfile
    container_name: jacq-wildfly
    depends_on:
      - db
    environment:
      VIRTUAL_HOST: ${DEFAULT_HOST}
      VIRTUAL_PORT: 8080
    expose:
      - 8080
      - 8443
    networks:
      - backend
      - frontend
    ports:
      - 8080:8080
      - 8443:8443
      - 9990:9990
      - 9991:9991
    restart: always
    volumes:
      - wildfly:/opt/jboss/wildfly

  gnparser:
    image: gnames/biodiversity
    container_name: jacq-biodiversity
    expose:
      - 4334
    networks:
      - frontend
    restart: always

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: jacq-nginx-proxy
    depends_on:
      - phpmyadmin
      - wildfly
    networks:
      - frontend
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always

networks:
  backend:
  frontend:

volumes:
  db:
  wildfly:
