version: "3"

services:
  db:
    image: mariadb:10
    container_name: jacq-db
    environment:
      MYSQL_DATABASE: ${DB}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    expose:
      - 3306
    networks:
      - backend
    restart: always
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - db:/var/lib/mysql

  wildfly:
    build:
      args:
        WILDFLY_USER: ${WILDFLY_USER}
        WILDFLY_PASSWORD: ${WILDFLY_PASSWORD}
      context: .
      dockerfile: Dockerfile
    container_name: jacq-wildfly
    depends_on:
      - db
    networks:
      - backend
      - frontend
    ports:
      - 8080:8080
      - 9990:9990
      - 9991:9991
    restart: always

  gnparser:
    image: gnames/biodiversity
    container_name: jacq-biodiversity
    networks:
      - frontend
    expose:
      - 4334
    restart: always

networks:
  frontend:
  backend:

volumes:
  db: {}
